# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rindert
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: takeawayapp
# "service" is the name of this project. This will also be added to your AWS resource names.
service: takeaway

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: arn:aws:iam::050451366469:role/lambda-full-access-dynamodb


functions:
  postMeny:
    handler: functions/postMeny/index.handler
    events:
      - httpApi:
          path: /post/meny
          method: post

  getDishes:
    handler: functions/getDishes/index.handler
    events:
      - httpApi:
          path: /get/meny
          method: get

  adminUpdate:
    handler: functions/adminUpdate/index.handler
    events:
      - httpApi:
          path: /update/{id}
          method: put

  orderFood:
    handler: functions/orderFood/index.handler
    events:
      - httpApi:
          path: /order/food
          method: post
  getOrder:
    handler: functions/getOrder/index.handler
    events:
      - httpApi:
          path: /order
          method: get

  adminOrderKlar:
    handler: functions/adminOrderKlar/index.handler
    events:
      - httpApi:
          path: /admin/order-klar
          method: put

  lockOrder:
    handler: functions/lockOrder/index.handler
    events:
      - http:
          path: order/lock
          method: post
         
  adminKommentar:
    handler: functions/adminKommentar/index.handler
    events:
      - http:
          path: admin/kommentar
          method: post      

resources:
  Resources:
    HerringTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'HerringDB'
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    HerringOrderTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: 'HerringOrder'
          AttributeDefinitions:
            - AttributeName: 'orderId'
              AttributeType: 'S'
          KeySchema:
            - AttributeName: 'orderId'
              KeyType: HASH
          BillingMode: PAY_PER_REQUEST