# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: stenelind
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: takeawayapp
# "service" is the name of this project. This will also be added to your AWS resource names.
service: takeaway

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: arn:aws:iam::711387100461:role/LambdaDynamoDBFull

functions:
  PostMeny:
    handler: functions/PostMeny/index.handler
    events:
      - httpApi:
          path: /post/meny
          method: post

  adminUpdate:
    handler: functions/adminUpdate/index.handler
    events:
      - httpApi:
          path: /update/{id}
          method: PUT       


resources:
  Resources:
    HerringTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'HerringDB'
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST