org: stenelind
app: takeawayapp
service: takeaway

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: arn:aws:iam::711387100461:role/LambdaDynamoDBFull
    
package:
  include:
    - data/keys.mjs

functions:
  postMenu:
    handler: functions/postMenu/index.handler
    events:
      - httpApi:
          path: /post/menu
          method: post

  getMenu:
    handler: functions/getMenu/index.handler
    events:
      - httpApi:
          path: /get/menu
          method: get

  adminUpdate:
    handler: functions/adminUpdate/index.handler
    events:
      - httpApi:
          path: /menu/update/{id}
          method: put

  orderFood:
    handler: functions/orderFood/index.handler
    events:
      - httpApi:
          path: /order/food
          method: post

  getOrder:
    handler: functions/getOrder/index.handler
    events:
      - httpApi:
          path: /order
          method: get

  adminOrderKlar:
    handler: functions/adminOrderKlar/index.handler
    events:
      - httpApi:
          path: /admin/order/klar
          method: put

  lockOrder:
    handler: functions/lockOrder/index.handler
    events:
      - httpApi:
          path: /admin/order/lock
          method: post

  getKeys:
    handler: functions/getKeys/index.handler
    events:
      - httpApi:
          path: /keys
          method: get

  adminKommentar:
    handler: functions/adminKommentar/index.handler
    events:
      - httpApi:
          path: /admin/kommentar
          method: post

  deleteOrder:
    handler: functions/deleteOrder/index.handler
    events:
      - httpApi:
          path: /admin/delete/order/{id}
          method: delete

  loginAdmin:
      handler: functions/loginAdmin/index.handler
      events:
        - httpApi:
            path: /admin/login
            method: post

resources:
  Resources:
    HerringTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'HerringDB'
        AttributeDefinitions:
          - AttributeName: 'id'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'id'
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    HerringOrderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'HerringOrder'
        AttributeDefinitions:
          - AttributeName: 'orderId'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'orderId'
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST